# Exercises for Lecture 11 (Introduction to TensorFlow)

In [1]:
import datetime
now = datetime.datetime.now()
print("Last executed: " + now.strftime("%Y-%m-%d %H:%M:%S"))

Last executed: 2022-02-04 11:53:26


In [2]:
import numpy as np
import tensorflow as tf

2022-02-04 11:53:26.630186: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-02-04 11:53:26.630212: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


## Exercise 1: Linear regression

### Load housing data

Load the California housing regression dataset.

In [3]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m, n = housing.data.shape
(m, n)

(20640, 8)

In [4]:
housing.target.shape

(20640,)

In [5]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

The dataset contains 8 features (displayed above) contained in `housing.data` that can be used to predict house prices (in units of $100,000), which are contained in `housing.targets`.

### Set up data (add bias and reshape data)

In [6]:
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]
housing_data_target = housing.target.reshape(-1, 1)

In [7]:
housing_data_target.shape, housing_data_plus_bias.shape

((20640, 1), (20640, 9))

Fit a linear regression model to the data, using a Scikit Learn LinearRegression model and then by computing the analytic solution using numpy and TensorFlow.  

Compare the fitted model between the different computations to ensure you get similar model parameters.

### Exercise 1a: Fit a linear regression model using Scikit Learn

Use the Scikit Learn LinearRegression model.

In [8]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(housing.data, housing_data_target)
print(np.r_[lin_reg.intercept_.reshape(-1, 1), lin_reg.coef_.T])

[[-3.69419202e+01]
 [ 4.36693293e-01]
 [ 9.43577803e-03]
 [-1.07322041e-01]
 [ 6.45065694e-01]
 [-3.97638942e-06]
 [-3.78654265e-03]
 [-4.21314378e-01]
 [-4.34513755e-01]]


### Exercise 1b: Fit a linear regression model using numpy

Solve the normal equations analytically.

In [9]:
X = housing_data_plus_bias
y = housing_data_target
theta_numpy = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
print(theta_numpy)

[[-3.69419202e+01]
 [ 4.36693293e-01]
 [ 9.43577803e-03]
 [-1.07322041e-01]
 [ 6.45065694e-01]
 [-3.97638942e-06]
 [-3.78654265e-03]
 [-4.21314378e-01]
 [-4.34513755e-01]]


### Exercise 1c: Fit a linear regression model using TensorFlow

Solve the normal equations analytically.

In [10]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing_data_target, dtype=tf.float32, name="y")
XT = tf.transpose(X)
theta_tf = tf.matmul(tf.matmul(tf.linalg.inv(tf.matmul(XT, X)), XT), y)
print(theta_tf)

tf.Tensor(
[[-3.71679459e+01]
 [ 4.36065614e-01]
 [ 9.39804502e-03]
 [-1.06580436e-01]
 [ 6.42261207e-01]
 [-4.06296385e-06]
 [-3.78040830e-03]
 [-4.23595876e-01]
 [-4.37090367e-01]], shape=(9, 1), dtype=float32)


2022-02-04 11:53:30.138835: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-02-04 11:53:30.138863: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-04 11:53:30.138880: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (fv-az91-45): /proc/driver/nvidia/version does not exist
2022-02-04 11:53:30.139159: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Exercise 2: Compute gradients

Compute the partial derivatives of the following function (`my_func`) at `(a,b) = (0.2,0.3)` by:
1. numerical integration 
2. Autodiff in TensorFlow 

Check you get the same answer in both cases.

In [11]:
def my_func(a, b):
    z = 0.0
    for i in range(100):
        z = a * np.cos(z + i) + z * np.sin(b - i)
    return z

### Compute by numerical integration

In [12]:
delta = 0.01
f = my_func
df_da = (f(0.2+delta,0.3) - f(0.2-delta,0.3))/(2*delta)
df_db = (f(0.2,0.3+delta) - f(0.2,0.3-delta))/(2*delta)
df_da, df_db

(-1.138390186170457, 0.19675140591134677)

### Compute using Autodiff in TensorFlow

In [13]:
a = tf.Variable(0.2, name="a")
b = tf.Variable(0.3, name="b")

In [14]:
with tf.GradientTape() as t:
    z = 0.0
    for i in range(100):
        z = a * tf.cos(z + i) + z * tf.sin(b - i)
    
gradients = t.gradient(z, [a, b])
print(gradients)

[<tf.Tensor: shape=(), dtype=float32, numpy=-1.1388494>, <tf.Tensor: shape=(), dtype=float32, numpy=0.19671395>]
